name: flutter_project_connectfour1
description: "A new Flutter project."

publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  go_router: ^13.2.0
  fluro: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/PermanentMarker-Regular.ttf
    - family: Lemon
      fonts:
        - asset: assets/Lemon-Regular.ttf